version: '2'
services:
    api:
        build: ./api/
        ports:
            - "3000:3000"
        networks:
            - typeracer
        volumes:
            - "./api:/api"
        entrypoint: "npm run start"
    app:
        build: ./app/
        ports:
            - "8080:8080"
        environment:
            - API_URL=http://api:3000
        networks:
            - typeracer
        volumes:
            - "./app:/app"
        entrypoint: "npm run start"
networks:
    typeracer: